### ISSUE TITLE
Custom Glyphs Sometimes Fail To Load With Newly Added Modules

### ISSUE THREAD

**Issue by Beazurt** [TBDFramework/TagEditorCore#110]
When adding a new search path to the editor, custom glyphs for any newly discovered modules sometimes fail to load.  Closing the editor and reopening that configuration seems to resolve the problem.

**Comment by dsmithni** [comment]
closed in CEF, default node now has the behavior to look in its local directory for the glyph it needs (and only that glyph) if it can't find it in the glyph manager already
