### ISSUE TITLE
Add better instructions to our common sample projects and scripts

### ISSUE THREAD

**Issue by Beazurt** [TBDFramework/TagEditorCore#116]
The Fixed-Channel Sample Project, Fixed-Channel Script, and Script Module Includes all assume a basic level of understanding from the user.  I think we should add better documentation on their Front Panels. 

The Fixed-Channel Sample Project should explain the difference between an Input, Output, Parameter, and Result.  

The Fixed-Channel Script should explain when it should be run and what it does.  It should also explain what the input, process, and output configurations are for (and that they don't need to be used at all unless you renamed something).

The Script Module Includes should explain what it's for, when it should be run, and what the Plugin Search Paths are for.

**Comment by dsmithni** [comment]
https://github.com/TBDFramework/TagBusSampleProjects/issues/1
