### ISSUE TITLE
Loading the Standard Configuration Editor From the Tools Menu is Slow and a Little Wonky

### ISSUE THREAD

**Issue by Beazurt** [TBDFramework/TagEditorCore#120]
Opening the Standard Editor from the LabVIEW Tools Menu is pretty slow.  It also shows the front panel of the launcher, then the front panel of the editor while not running, then the front panel of the editor loading splash screen, and finally shows the running editor UI.  It would be great if we simply saw a busy cursor until the Editor's loading splash screen was ready to run.

**Comment by dsmithni** [comment]
other solution is not valid, reopening this one

**Comment by Beazurt** [comment]
Are there things we can do to limit the wonkiness even if its still slow?  Ideally we could show the splash screen more quickly, or just show a busy cursor until the splash screen finally loads.
