### ISSUE TITLE
Adding Status to Module Glyph Should Be Handled By Parent Function

### ISSUE THREAD

**Issue by Beazurt** [TBDFramework/TagEditorCore#122]
When implementing your own Get Text function to change your program's glyph, you have to be sure to use the 'Add status to name.vi'.  At the very least we should document this better in the parent functions, but ideally we should have the framework append this information for a user.

**Comment by dsmithni** [comment]
Done here:
https://github.com/NISystemsEngineering/CEF/commit/26ed3f56bf208634f188536d6ba85199878bbfee
Now we just have to delete all the code from existing nodes.
There is a new method called "get overlay" which is where the validation check occurs and is called whenever the tree updates. Tree can now be updated via user event.
