### ISSUE TITLE
Deploy Tool Should Check for Unsaved Changes

### ISSUE THREAD

**Issue by Beazurt** [TBDFramework/TagEditorCore#150]
Yes people should learn to save before deploying, but a simple mistake here can cost a lot of time debugging.  There are a few ways to do this, (autosave, notify, request save or cancel) but a user should get some feedback that they have unsaved changes before they deploy.

**Comment by dsmithni** [comment]
should be able to just add that to the message queue in the editor. I think "Save?" is the message.

**Comment by Beazurt** [comment]
Added a new 'DeployTool?' message that works like the others.
