### ISSUE TITLE
Deleting tags with "minus" button does not remove the selected tag.

### ISSUE THREAD

**Issue by leesecho** [TBDFramework/TagEditorCore#151]
In the Standard Engine > Tags pane, the "minus" button removes cells which do not correspond to the currently selected cell.

**Comment by dsmithni** [comment]
this is due to active cell returning a nonsensical value (when row 1 is selected it output 7 when we debugged)

**Comment by dsmithni** [comment]
edit cell doesnt work *either*
seems to be we want "selection start.row"
