### ISSUE TITLE
Remove FPGA dependecies in Parent Class

### ISSUE THREAD

**Issue by becega** [TBDFramework/TagEditorCore#166]
The parent class runtime requires to have RIO driver installed. This is an issue when deploying to cDAQ chassis.
In PL_Target Runtime.lvclass Initialize.vi
![pltarget init](https://cloud.githubusercontent.com/assets/5290634/8368744/15487cb4-1b74-11e5-86b8-c5d11d1aba54.PNG)
and in PL_Target Runtime.lvclass  Shutdown.vi
![pl target shutdown](https://cloud.githubusercontent.com/assets/5290634/8368757/41696d26-1b74-11e5-8329-c11534f63362.PNG)

**Comment by smithed** [comment]
did you finish this?

**Comment by becega** [comment]
Yes
