### ISSUE TITLE
Overall Config. Valid Checking in the Editor

### ISSUE THREAD

**Issue by Beazurt** [TBDFramework/TagEditorCore#23]
A user of the editor today is only notified of an invalid configuration after saving it.  They also are only notified with a red X in their icons.  A user should get feedback as soon as they click off of their plugin that it is invalid with the icon change.  If they attempt to save an invalid config, they should be notified.  Finally, a user should be able to right-click an icon with a red X and get information as to why it is invalid.  Implementation details could vary here, but overall this concept still needs a lot of work.

**Comment by dsmithni** [comment]
partially implemented in CEF. Still needs nodes to notify when changes occur but there is now a way to do so.

**Comment by dsmithni** [comment]
get node info now returns error or warning from config valid

**Comment by dsmithni** [comment]
remove last update, now added here
https://github.com/NISystemsEngineering/CEF/issues/56
