### ISSUE TITLE
Key Value Table Doesn't Allow Selection of Empty Values

### ISSUE THREAD

**Issue by Beazurt** [TBDFramework/TagEditorCore#97]
The Edit Cell event doesn't get thrown if the cell is initially empty.  We should initialize the cell to a non-empty value and prevent users from changing the value to empty.  Alternatively we could use a different mechanism for changing cell values.

**Comment by dsmithni** [comment]
totally works, just tested it with a standalone VI

**Comment by Beazurt** [comment]
I just tried this again with the Watchdog Fixed-Channel in the Sample Application and it still doesn't work for me.  Could this be an issue with a subpanel?  I can't figure out how to fix it.

**Comment by dsmithni** [comment]
![untitled](https://cloud.githubusercontent.com/assets/7308102/5878760/e792712e-a2ee-11e4-8b70-fde31afac32c.png)
Works just fine

**Comment by Beazurt** [comment]
What magic do you have?  Did you just double-click? I tried everything and it never works for me.

**Comment by dsmithni** [comment]
click slower or tripleclick. Its the same magic you have to have to edit conditional disable flags, since they also use the mclb. There might be some way to make it work better but it does work.
